### PR TITLE
feat: support `redirectURL` config for all providers

### LINKED ISSUE #117: Keycloak Auth failing in production on setUserSession call
When I run the same build in production Heroku environment I can see the user gets redirected to keycloak... The user adds username/password credentials and is redirected back with success. The code calls the setUserSession and results in the stack trace below. The same code runs to the sendRedirect section of the code in my local development environment. Have I configured something incorrectly that is required for production?
`2024-07-08T10:45:05.747311+00:00 app[web.1]: [nuxt] [request error] [unhandled] [500] Empty password
2024-07-08T10:45:05.747327+00:00 app[web.1]:   at seal (./.output/server/chunks/runtime.mjs:1664:11)  
2024-07-08T10:45:05.747328+00:00 app[web.1]:   at sealSession (./.output/server/chunks/runtime.mjs:3532:24)  
2024-07-08T10:45:05.747329+00:00 app[web.1]:   at updateSession (./.output/server/chunks/runtime.mjs:3520:26)  
2024-07-08T10:45:05.747329+00:00 app[web.1]:   at getSession (./.output/server/chunks/runtime.mjs:3506:11)  
2024-07-08T10:45:05.747330+00:00 app[web.1]:   at useSession (./.output/server/chunks/runtime.mjs:3448:9)  
2024-07-08T10:45:05.747330+00:00 app[web.1]:   at _useSession (./.output/server/chunks/runtime.mjs:6634:10)  
2024-07-08T10:45:05.747330+00:00 app[web.1]:   at setUserSession (./.output/server/chunks/runtime.mjs:6609:25)  
2024-07-08T10:45:05.747330+00:00 app[web.1]:   at onSuccess (./.output/server/chunks/routes/auth/keycloak.get.mjs:1048:11) `

### LINKED ISSUE #137: ability to specify redirect_uri for google and github - allows compatibility with CloudFront+Lambda
It would be nice to be able to specify the `redirect_uri` - I have a production setup on AWS Lambda+Cloudfront deployed via [fume](https://fume.app)

 - in the Google dev console  i have https://domain/api/oauth/google
 - when i get the 400: redirect_uri_mismatch, google doesn't see cloudfront, so [this line here](https://github.com/atinux/nuxt-auth-utils/blob/0345169251c9c7d45a436090f2647bf8b7df1b96/src/runtime/server/lib/oauth/google.ts#L84) actually sees `https://mkniuoyitj.execute-api.us-east-1.amazonaws.com/api/oauth/google` - which while is possibly fixable - this would definitely change on a per-environment basis.

image

I will work on a PR as soon as i find time

### PR DESCRIPTION
**Pull request by acidjazz**
Fixes #137 
Fixes #117

### CODE REVIEW

**Review by mfreeman451 — APPROVED** [review]

**Comment by atinux** [comment]
cc @tcarterBAMF I renamed `config.redirectUrl` to `config.redirectURL`, if you use the `NUXT_OAUTH_MICROSOFT_REDIRECT_URL` env variable it should work without issue.

**Comment by buff** [comment]
This change seems to only be for google and microsoft... Will it also be applied to keycloak??

**Comment by acidjazz** [comment]
> This change seems to only be for google and microsoft... Will it also be applied to keycloak??

yes, every provider

**Comment by buff** [comment]
@acidjazz Thankx... I have tested the latest changes for keycloak and it seems to be 100%

**Pull request merged**
