### PR TITLE
feat: added keycloak as oauth provider

### PR DESCRIPTION
**Pull request by kingyue737**
Added keycloak as provider

### CODE REVIEW

**Comment by kingyue737** [comment]
Tested locally

image

**Comment by Atinux** [comment]
Happy to resolve the fonclits?

**Comment by kingyue737** [comment]
@Atinux Conflicts resolved!

**Review by Atinux — APPROVED** [review]

**Comment by kardossandor** [comment]
Are you planning to handle refresh tokens as well?

**Comment by Atinux** [comment]
PR welcome to help :)

**Comment by abasu0713** [comment]
any update on refresh tokens?

**Pull request merged**
